// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHRzRnzNELiyw_pL7_F0YkbQkW2ivEiCw',
    appId: '1:533421577406:web:8fc3a790d4e90f7f193aef',
    messagingSenderId: '533421577406',
    projectId: 'the-fashion-store-68bbe',
    authDomain: 'the-fashion-store-68bbe.firebaseapp.com',
    storageBucket: 'the-fashion-store-68bbe.appspot.com',
    measurementId: 'G-LE1QP5N425',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3DI_Sma8TvGvdKef9WxbqTTCmE37pcb0',
    appId: '1:533421577406:android:389769bed364da12193aef',
    messagingSenderId: '533421577406',
    projectId: 'the-fashion-store-68bbe',
    storageBucket: 'the-fashion-store-68bbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC5uenjsYOBxB4zF8x7oAPBZXMLOlYvng',
    appId: '1:533421577406:ios:ea8988314f840908193aef',
    messagingSenderId: '533421577406',
    projectId: 'the-fashion-store-68bbe',
    storageBucket: 'the-fashion-store-68bbe.appspot.com',
    iosBundleId: 'com.fashionstore.fashionStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC5uenjsYOBxB4zF8x7oAPBZXMLOlYvng',
    appId: '1:533421577406:ios:42a66dabc95272f9193aef',
    messagingSenderId: '533421577406',
    projectId: 'the-fashion-store-68bbe',
    storageBucket: 'the-fashion-store-68bbe.appspot.com',
    iosBundleId: 'com.fashionstore.fashionStore.RunnerTests',
  );
}
